---
name: rundeck-issue-5398-example-plugin
description: ""
rundeckPluginVersion: 1.2
author: "Thomas Løkkeborg <thomas.loekkeborg@cern.ch>"
date: "2019-10-21"
version: 1.0.0
url: ""
tags:
  - script
providers:
  - name: rundeck-issue-5398-example-plugin-execute-script
    service: WorkflowNodeStep
    title: 'Issue 5398 example'
    description: 'Issue 5398 example'
    plugin-type: script
    script-interpreter: python -u
    script-file: example-script.py
    script-args:
    config:
      - name: script_config_opt
        type: String
        title: "Script"
        description: ""
        default: |
          # the following will not output the value of the job option, it will
          # just output @option.testoption@ literally
          echo "@option.testoption@"
          
          # the following will output the value of the job option, but at the
          # cost of the next example breaking...
          echo "${option.testoption}"

          # the following will output an empty string, as Rundeck will
          # substitute ${testvariable} to an empty string (it thinks that it is
          # an ${option.something} ?)
          testvariable='testvalue'
          echo "${testvariable}"

          # in most cases it's possible to avoid the ${var} syntax by doing
          # $var, but sometimes ${...} is needed. For example trying to print a
          # Bash array will cause Rundeck substitution to get confused
          myarray=(1 2 3)
          echo "${myarray[@]}"
        required: true
        renderingOptions:
          displayType: CODE
